In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8806, 6056, 1004, 4265],
 [8806, 6056, 1004, 410],
 [8806, 7261, 1004, 419],
 [7725, 892, 7382, 467, 6366],
 [7725, 892, 7382, 467, 1802],
 [6678, 8806, 5732, 1004, 2028],
 [1974, 2405, 8108, 467]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [10]:
#make sentences equal size
sent_length=8
# añade los ceros faltantes a 8 de long total, antes o despues en este caso antes
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length) 
print(embedded_docs)

[[   0    0    0    0 8806 6056 1004 4265]
 [   0    0    0    0 8806 6056 1004  410]
 [   0    0    0    0 8806 7261 1004  419]
 [   0    0    0 7725  892 7382  467 6366]
 [   0    0    0 7725  892 7382  467 1802]
 [   0    0    0 6678 8806 5732 1004 2028]
 [   0    0    0    0 1974 2405 8108  467]]


In [11]:
## feature representation
dim=10


In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 93ms/step


array([[[-4.1732937e-04, -4.1833948e-02, -4.7946837e-02, -4.5998216e-02,
         -2.9656066e-02, -3.4509301e-03, -2.3377968e-02,  4.0701497e-02,
         -1.0657240e-02,  8.4102042e-03],
        [-4.1732937e-04, -4.1833948e-02, -4.7946837e-02, -4.5998216e-02,
         -2.9656066e-02, -3.4509301e-03, -2.3377968e-02,  4.0701497e-02,
         -1.0657240e-02,  8.4102042e-03],
        [-4.1732937e-04, -4.1833948e-02, -4.7946837e-02, -4.5998216e-02,
         -2.9656066e-02, -3.4509301e-03, -2.3377968e-02,  4.0701497e-02,
         -1.0657240e-02,  8.4102042e-03],
        [-4.1732937e-04, -4.1833948e-02, -4.7946837e-02, -4.5998216e-02,
         -2.9656066e-02, -3.4509301e-03, -2.3377968e-02,  4.0701497e-02,
         -1.0657240e-02,  8.4102042e-03],
        [-2.3536896e-02, -2.0842612e-02, -2.1646643e-02,  1.4174495e-02,
         -1.2706887e-02, -4.1415811e-02,  3.0707899e-02, -4.6503555e-02,
          4.3178547e-02,  1.8608082e-02],
        [ 3.1757247e-02, -1.5112162e-02, -4.0570460e-02, -1.

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 8806, 6056, 1004, 4265])

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 36ms/step


array([[-0.00041733, -0.04183395, -0.04794684, -0.04599822, -0.02965607,
        -0.00345093, -0.02337797,  0.0407015 , -0.01065724,  0.0084102 ],
       [-0.00041733, -0.04183395, -0.04794684, -0.04599822, -0.02965607,
        -0.00345093, -0.02337797,  0.0407015 , -0.01065724,  0.0084102 ],
       [-0.00041733, -0.04183395, -0.04794684, -0.04599822, -0.02965607,
        -0.00345093, -0.02337797,  0.0407015 , -0.01065724,  0.0084102 ],
       [-0.00041733, -0.04183395, -0.04794684, -0.04599822, -0.02965607,
        -0.00345093, -0.02337797,  0.0407015 , -0.01065724,  0.0084102 ],
       [-0.0235369 , -0.02084261, -0.02164664,  0.01417449, -0.01270689,
        -0.04141581,  0.0307079 , -0.04650356,  0.04317855,  0.01860808],
       [ 0.03175725, -0.01511216, -0.04057046, -0.01345602, -0.03531672,
         0.04363767, -0.00955156,  0.03946495,  0.00436425,  0.02306706],
       [ 0.00917021, -0.03178544, -0.00170768,  0.01549884, -0.00111185,
        -0.01462836, -0.04865515,  0.03184834